const UPDATE_QUERYS_SEARCH = "UPDATE_QUERYS_SEARCH";
const UPDATE_QUERYS_PAGINATE = "UPDATE_QUERYS_PAGINATE";
const UPDATE_QUERYS_FILTER = "UPDATE_QUERYS_FILTER";
const UPDATE_QUERYS_ORDER = "UPDATE_QUERYS_ORDER";
const UPDATE_URL = "UPDATE_URL";
const UPDATE_CURRENT_PAGE = "SET_CURRENT_PAGE";
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
const GET_CATEGORIES = "GET_CATEGORIES";
const GET_SUB = "GET_SUB";
const GET_FEATURES = "GET_FEATURES";
const GET_PATH = "GET_PATH"

const GET_USER = "GET_USER";
const ERROR = "ERROR";
const LOGIN_USER = "LOGIN_USER";
const REGISTER_USER = "REGISTER_USER";
const LOGOUT_USER = "LOGOUT_USER";
const LOADING_USER = "LOADING_USER";

export {
  UPDATE_QUERYS_FILTER,
  UPDATE_QUERYS_ORDER,
  UPDATE_QUERYS_PAGINATE,
  UPDATE_QUERYS_SEARCH,
  UPDATE_URL,
  UPDATE_CURRENT_PAGE,
  GET_ALL_PRODUCTS,
  GET_CATEGORIES,
  GET_SUB,
  GET_FEATURES,
  GET_PATH,
  
  GET_USER,
  LOGIN_USER,
  REGISTER_USER,
  LOGOUT_USER,
  ERROR,
  LOADING_USER
};
